#!/usr/bin/env node
// Snapshots design-system/tokens.json, diffs it against the previous snapshot, and
// records the result in history.json (structured, consumed by the Storybook Changelog
// page) and CHANGELOG.md (human-readable). Run via `npm run tokens:sync`.

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

import { classify, deref, flattenTokens, formatValue, loadJson, stableStringify, toCssColor } from "./resolve-tokens.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TOKENS_PATH = path.join(__dirname, "..", "tokens.json");
const SNAPSHOT_PATH = path.join(__dirname, "snapshot.json");
const HISTORY_PATH = path.join(__dirname, "history.json");
const MARKDOWN_PATH = path.join(__dirname, "CHANGELOG.md");

function readHistory() {
    return existsSync(HISTORY_PATH) ? loadJson(HISTORY_PATH) : [];
}

function readSnapshot() {
    return existsSync(SNAPSHOT_PATH) ? loadJson(SNAPSHOT_PATH) : null;
}

function summarize(changes) {
    const counts = { changed: 0, added: 0, removed: 0 };
    for (const change of changes) counts[change.status]++;
    return `${counts.changed} changed, ${counts.added} added, ${counts.removed} removed`;
}

function changeLine(change) {
    const icon = change.status === "added" ? "➕" : change.status === "removed" ? "➖" : "🔄";
    const label = change.status === "added" ? "Added" : change.status === "removed" ? "Removed" : "Changed";
    const before = change.before ?? "—";
    const after = change.after ?? "—";
    const description = change.description ? ` — _${change.description}_` : "";
    return `- ${icon} **${label}** \`${change.path}\`: \`${before}\` → \`${after}\`${description}`;
}

function renderMarkdown(history) {
    const header = [
        "# Token Changelog",
        "",
        "Tracks changes to `design-system/tokens.json` on each sync. Generated by " +
            "`design-system/changelog/sync.mjs` — do not edit by hand.",
        "",
    ];

    if (history.length === 0) {
        return [...header, "_No syncs recorded yet._", ""].join("\n");
    }

    const sections = history.map((entry) => {
        const lines = [`## ${entry.timestamp}`, "", `**${entry.summary}**`, ""];
        for (const change of entry.changes) lines.push(changeLine(change));
        lines.push("");
        return lines.join("\n");
    });

    return [...header, ...sections].join("\n");
}

function buildChange(status, tokenPath, description, tree, rawValue) {
    const resolved = deref(tree, rawValue);
    const kind = classify(resolved);
    const formatted = formatValue(kind, resolved);
    const color = kind === "color" ? toCssColor(resolved) : undefined;

    const change = { path: tokenPath, status, kind, description };
    if (status === "removed") {
        change.before = formatted;
        change.after = null;
        if (color) change.beforeColor = color;
    } else {
        change.before = null;
        change.after = formatted;
        if (color) change.afterColor = color;
    }
    return change;
}

function main() {
    mkdirSync(__dirname, { recursive: true });

    const currentTree = loadJson(TOKENS_PATH);
    const previousTree = readSnapshot();

    if (!previousTree) {
        writeFileSync(SNAPSHOT_PATH, JSON.stringify(currentTree, null, 2) + "\n");
        if (!existsSync(HISTORY_PATH)) writeFileSync(HISTORY_PATH, "[]\n");
        if (!existsSync(MARKDOWN_PATH)) writeFileSync(MARKDOWN_PATH, renderMarkdown([]));
        console.log("No prior snapshot found — baseline snapshot created. Nothing to diff yet.");
        return;
    }

    const oldLeaves = flattenTokens(previousTree);
    const newLeaves = flattenTokens(currentTree);
    const allPaths = [...new Set([...oldLeaves.keys(), ...newLeaves.keys()])].sort();

    const changes = [];

    for (const tokenPath of allPaths) {
        const before = oldLeaves.get(tokenPath);
        const after = newLeaves.get(tokenPath);

        if (before && !after) {
            changes.push(buildChange("removed", tokenPath, before.description, previousTree, before.value));
            continue;
        }

        if (after && !before) {
            changes.push(buildChange("added", tokenPath, after.description, currentTree, after.value));
            continue;
        }

        if (stableStringify(before.value) === stableStringify(after.value)) continue;

        const resolvedBefore = deref(previousTree, before.value);
        const resolvedAfter = deref(currentTree, after.value);
        const kindBefore = classify(resolvedBefore);
        const kindAfter = classify(resolvedAfter);

        const change = {
            path: tokenPath,
            status: "changed",
            kind: kindAfter,
            description: after.description,
            before: formatValue(kindBefore, resolvedBefore),
            after: formatValue(kindAfter, resolvedAfter),
        };
        if (kindBefore === "color") change.beforeColor = toCssColor(resolvedBefore);
        if (kindAfter === "color") change.afterColor = toCssColor(resolvedAfter);
        changes.push(change);
    }

    writeFileSync(SNAPSHOT_PATH, JSON.stringify(currentTree, null, 2) + "\n");

    if (changes.length === 0) {
        console.log("No token changes detected since last sync.");
        return;
    }

    const timestamp = new Date().toISOString();
    const entry = { id: timestamp, timestamp, summary: summarize(changes), changes };

    const history = readHistory();
    history.unshift(entry);

    writeFileSync(HISTORY_PATH, JSON.stringify(history, null, 2) + "\n");
    writeFileSync(MARKDOWN_PATH, renderMarkdown(history));

    console.log(`Recorded ${changes.length} token change(s): ${entry.summary}`);
    for (const change of changes) console.log(`  ${changeLine(change)}`);
}

main();
